---
services:
  intranet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: unless-stopped
    volumes:
      - ./documents:/code/documents
      - ./document_templates:/code/document_templates
    environment:
      DB_HOST: intranet-mssql
      DB_USER: sa
      DB_NAME: Intranet
      DB_PASSWORD: Pass12345
      DOC_LANGUAGE: en
      DB_MIGRATE: true
      TZ: Asia/Tbilisi
    networks:
      - intranet


networks:
  intranet:
    external: true
